# Generated by Django 6.0.3 on 2026-03-08 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongPopularity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='popularity', to='music.song')),
            ],
        ),
    ]
